# Generated by Django 6.0 on 2026-01-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='street',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='field',
            field=models.CharField(max_length=6),
        ),
    ]
