# Generated by Django 6.0 on 2026-01-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='residenthome',
            old_name='person',
            new_name='resident',
        ),
    ]
