# Generated by Django 6.0 on 2026-01-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('R', 'Residente'), ('V', 'Visitante'), ('W', 'Worker')], max_length=1)),
                ('photo', models.CharField(max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('AL', 'Auxiliar de Limpeza'), ('G', 'Guarda'), ('J', 'Jardineiro(a)'), ('E', 'Eletricista'), ('EA', 'Entregador(a) de Água'), ('O', 'Outro')], max_length=3)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='worker', to='people.person')),
                ('work_for', models.ManyToManyField(related_name='bosses', to='people.person')),
            ],
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='residents',
            name='home',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residents',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resident', to='people.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='host',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hosts', to='people.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitor',
            name='person',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='visitor', to='people.person'),
            preserve_default=False,
        ),
    ]
