# Generated by Django 6.0 on 2026-01-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_home_street_alter_worker_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='bi',
            field=models.CharField(default=None, max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='bi',
            field=models.CharField(default=None, max_length=14, unique=True),
            preserve_default=False,
        ),
    ]
