# Generated by Django 6.0 on 2026-01-17 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0003_alter_worker_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="worker",
            old_name="field",
            new_name="fields",
        ),
    ]
