# Generated by Django 6.0 on 2026-01-14 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_resident_bi_worker_bi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorhost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.resident'),
        ),
    ]
