# Generated by Django 6.0 on 2026-01-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_alter_resident_person_alter_residenthome_resident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='type',
            field=models.CharField(choices=[('VR', 'Visitanto residente'), ('EMP', 'Procurando emprego'), ('ENT', 'Entregador'), ('PS', 'Prestador de serviço'), ('O', 'Outro')], default=None, max_length=3),
            preserve_default=False,
        ),
    ]
