# Generated by Django 6.0 on 2026-01-29 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_visitor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person'),
        ),
    ]
