# Generated by Django 6.0 on 2026-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0008_alter_resident_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visitor",
            name="type",
            field=models.CharField(
                choices=[
                    ("VR", "Visitanto residente"),
                    ("PE", "Procurando emprego"),
                    ("PS", "Prestador de serviço"),
                    ("E", "Entregador"),
                    ("O", "Outro(a)"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="fields",
            field=models.CharField(
                choices=[
                    ("G", "Guarda"),
                    ("M", "Motorista"),
                    ("E", "Electricista"),
                    ("J", "Jardineiro(a)"),
                    ("AL", "Auxiliar de Limpeza"),
                    ("MA", "Membro da Administração"),
                    ("O", "Outra(a)"),
                ],
                max_length=30,
            ),
        ),
    ]
