# Generated by Django 6.0 on 2026-02-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0010_alter_worker_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="person",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="type",
            field=models.CharField(
                choices=[
                    ("VR", "Visitando residente"),
                    ("PE", "Procurando emprego"),
                    ("PS", "Prestador de serviço"),
                    ("E", "Entregador"),
                    ("O", "Outro(a)"),
                ],
                max_length=3,
            ),
        ),
    ]
