# Generated by Django 6.0 on 2026-02-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0012_merge_20260217_0123"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitorhost",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
