# Generated by Django 6.0 on 2026-03-29 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_visit_visitdestiny_delete_visitorhost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='resident',
            options={'verbose_name': 'Residente', 'verbose_name_plural': 'Residentes'},
        ),
        migrations.AlterModelOptions(
            name='residenthome',
            options={'verbose_name': 'Casa do Residente', 'verbose_name_plural': 'Casas dos Residentes'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Visita', 'verbose_name_plural': 'Visitas'},
        ),
        migrations.AlterModelOptions(
            name='visitdestiny',
            options={'verbose_name': 'Destino da Visita', 'verbose_name_plural': 'Destinos das Visitas'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Trabalhador', 'verbose_name_plural': 'Trabalhadores'},
        ),
        migrations.AlterModelOptions(
            name='workerhome',
            options={'verbose_name': 'Casa de trabalho do trabalhador', 'verbose_name_plural': 'Casas de trabalho dos trabalhadores'},
        ),
        migrations.AlterField(
            model_name='home',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='home',
            name='street',
            field=models.CharField(max_length=30, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='person',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Adição'),
        ),
        migrations.AlterField(
            model_name='person',
            name='banned',
            field=models.BooleanField(default=False, verbose_name='Banido'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type',
            field=models.CharField(choices=[('R', 'Residente'), ('V', 'Visitante'), ('W', 'Trabalhador')], max_length=1, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Actualizaçõa'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='bi',
            field=models.CharField(max_length=14, unique=True, verbose_name='Bilhete de Identidade'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='residenthome',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.home', verbose_name='Casa'),
        ),
        migrations.AlterField(
            model_name='residenthome',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.resident', verbose_name='Residente'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data da Visita'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.visitor', verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='visitdestiny',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.resident', verbose_name='Residente'),
        ),
        migrations.AlterField(
            model_name='visitdestiny',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.visit', verbose_name='Visitante'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='type',
            field=models.CharField(choices=[('VR', 'Visitando residente'), ('PE', 'Procurando emprego'), ('PS', 'Prestador de serviço'), ('E', 'Entregador'), ('O', 'Outro(a)')], max_length=3, verbose_name='Tipo de Visitante'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='bi',
            field=models.CharField(max_length=14, unique=True, verbose_name='Bilhete de Identidade'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='fields',
            field=models.CharField(max_length=30, verbose_name='Áreas de Trabalho'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker', to='people.person', verbose_name='Pessoa'),
        ),
        migrations.AlterField(
            model_name='workerhome',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.home', verbose_name='Casa'),
        ),
        migrations.AlterField(
            model_name='workerhome',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.worker', verbose_name='Trabalhador'),
        ),
    ]
