# Generated by Django 6.0 on 2026-04-17 05:33

import apps.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0015_alter_home_options_alter_person_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='people_photos/', validators=[apps.people.models.validate_file_size]),
        ),
    ]
