services:
  web:
    build: ./web
    container_name: secureit-web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_6tx7OljCsDpA@ep-young-union-asboe64e-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - JWT_SECRET=x4$n!bnme4(khao6sy@8t*x&d1jn@#xk4^*u41-v20=5(2c55-
      - CI=true
    depends_on:
      db:
        condition: service_healthy

  api:
    build: ./desktop/api
    container_name: secureit-api
    ports:
      - "8000:8000"
    volumes:
      - ./desktop/api:/app
    privileged: true
    environment:
      - DEBUG=1
    depends_on:
      db:
        condition: service_healthy

  desktop:
    build: ./desktop
    container_name: secureit-desktop
    ports:
      - "1420:1420"
      - "1421:1421"
    volumes:
      - ./desktop:/app
      - /app/node_modules
    environment:
      - TAURI_DEV_HOST=0.0.0.0
      - CI=TAURI_DEV_HOST
      - VITE_API_URL=http://localhost:8000
      # - VITE_WEB_URL=https://secureit-web.ag-fran-dev.workers.dev/
      - VITE_WEB_URL=http://localhost:3000

    depends_on:
      - api
      - web

  db:
    image: pgvector/pgvector:pg16
    container_name: secureit-db
    environment:
      POSTGRES_USER: secureit
      POSTGRES_PASSWORD: secureit
      POSTGRES_DB: secureit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secureit"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
