[project]
name = "secureit"
version = "0.1.0"
description = "SecureIT: A segurança mais próximo de si."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "channels>=4.3.2",
    "cv2-enumerate-cameras>=1.3.1",
    "daphne>=4.2.1",
    "django>=6.0",
    "django-debug-toolbar>=6.2.0",
    "django-google-fonts>=0.0.3",
    "django-stubs>=5.2.9",
    "django-tailwind[cookiecutter,honcho,reload]>=4.4.2",
    "facenet-pytorch>=2.5.3",
    "imutils>=0.5.4",
    "lucide>=1.1.3",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "orjson>=3.11.7",
    "pillow>=12.1.0",
    "sqlite-vec>=0.1.6",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "ultralytics>=8.4.17",
]

[tool.taskipy.tasks]
run = "python manage.py runserver"
urun = "gunicorn core.asgi:application -k uvicorn_worker.UvicornWorker"
mg = "python manage.py migrate && python apps/people/db.py"
mkmg = "python manage.py makemigrations"
app = "python manage.py startapp"
