# Generated by Django 6.0 on 2026-01-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='name',
        ),
    ]
