# Generated by Django 6.0 on 2025-12-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='ativa',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='criada_em',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='localizacao',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='url_stream',
        ),
        migrations.AddField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='stream_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='type',
            field=models.CharField(blank=True, choices=[('I', 'Interna'), ('W', 'Wi-Fi')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
