# Generated by Django 6.0 on 2025-12-31 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_remove_camera_ativa_remove_camera_criada_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='stream_url',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='type',
        ),
        migrations.CreateModel(
            name='LocalCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
            ],
        ),
        migrations.CreateModel(
            name='WifiCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('stream_url', models.URLField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameras.camera')),
            ],
        ),
    ]
