# Generated by Django 6.0 on 2025-12-31 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_remove_camera_stream_url_remove_camera_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wificamera',
            name='ip_address',
        ),
    ]
