# Generated by Django 6.0 on 2025-12-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_remove_wificamera_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='connection_type',
            field=models.CharField(blank=True, choices=[('L', 'Local'), ('W', 'Wi-Fi')], max_length=1, null=True),
        ),
    ]
