# Generated by Django 6.0 on 2025-12-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camera_connection_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localcamera',
            name='device',
        ),
        migrations.AddField(
            model_name='localcamera',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
