# Generated by Django 6.0 on 2026-02-18 00:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fps', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('monitoring_start_time', models.TimeField(blank=True, null=True)),
                ('monitoring_end_time', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
