# Generated by Django 6.0 on 2026-02-18 00:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("panel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserConfiguration",
            new_name="Configuration",
        ),
    ]
