# Generated by Django 6.0 on 2026-03-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_configuration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='allow_draw',
            field=models.BooleanField(default=True, verbose_name='Permitir desenho'),
        ),
    ]
