# Generated by Django 6.0 on 2026-03-29 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_configuration_allow_draw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='alert_cooldown',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo de espera extra (segundos)'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='detect_every',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de frames a detectar'),
        ),
    ]
