#!/bin/sh

./scripts/sync-pkgs.sh

git add desktop/src/packages mobile/packages web/src/packages

if ! git diff --cached --quiet; then
    echo "Amending last commit with synced packages..."
    git commit --amend --no-edit
fi