// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/licenses" | "/admin/licenses/[id]" | "/admin/licenses/generate" | "/admin/login" | "/admin/payment-info" | "/admin/payments" | "/admin/plans" | "/login" | "/my-account" | "/signup"
type AppRouteHandlerRoutes = "/api/admin/licenses" | "/api/admin/licenses/[id]" | "/api/admin/licenses/generate" | "/api/admin/login" | "/api/admin/payment-info" | "/api/admin/payments" | "/api/admin/payments/[id]" | "/api/admin/plans" | "/api/auth/accounts" | "/api/auth/check-email" | "/api/auth/email-code/send" | "/api/auth/email-code/verify" | "/api/auth/login" | "/api/auth/logout" | "/api/auth/me" | "/api/auth/pin" | "/api/auth/pin-login" | "/api/auth/refresh" | "/api/auth/signup" | "/api/auth/totp/setup" | "/api/auth/totp/verify" | "/api/licenses/activate" | "/api/licenses/validate" | "/api/my-account/license" | "/api/payments" | "/api/payments/submit" | "/api/plans" | "/api/profiles" | "/api/profiles/[id]" | "/api/profiles/[id]/select" | "/api/sign-cloudinary-params"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/my-account"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/licenses": {}
  "/admin/licenses/[id]": { "id": string; }
  "/admin/licenses/generate": {}
  "/admin/login": {}
  "/admin/payment-info": {}
  "/admin/payments": {}
  "/admin/plans": {}
  "/api/admin/licenses": {}
  "/api/admin/licenses/[id]": { "id": string; }
  "/api/admin/licenses/generate": {}
  "/api/admin/login": {}
  "/api/admin/payment-info": {}
  "/api/admin/payments": {}
  "/api/admin/payments/[id]": { "id": string; }
  "/api/admin/plans": {}
  "/api/auth/accounts": {}
  "/api/auth/check-email": {}
  "/api/auth/email-code/send": {}
  "/api/auth/email-code/verify": {}
  "/api/auth/login": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/pin": {}
  "/api/auth/pin-login": {}
  "/api/auth/refresh": {}
  "/api/auth/signup": {}
  "/api/auth/totp/setup": {}
  "/api/auth/totp/verify": {}
  "/api/licenses/activate": {}
  "/api/licenses/validate": {}
  "/api/my-account/license": {}
  "/api/payments": {}
  "/api/payments/submit": {}
  "/api/plans": {}
  "/api/profiles": {}
  "/api/profiles/[id]": { "id": string; }
  "/api/profiles/[id]/select": { "id": string; }
  "/api/sign-cloudinary-params": {}
  "/login": {}
  "/my-account": {}
  "/signup": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/my-account": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
