# name: Pre-Deploy Actions

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "web/**"

# jobs:
#   deploy:
#     name: Deploy to Cloudflare
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Apply D1 Migrations
#         run: bunx wrangler d1 migrations apply secureit --remote
#         working-directory: web

#       - name: Deploy with Wrangler
#         uses: cloudflare/wrangler-action@v3
#         with:
#           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           command: deploy
#           workingDirectory: web
