name: Deploy Web

on:
  push:
    branches:
      - main
    # paths:
    #   - "web/**"

jobs:
  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Change directory
        run: cd web && pwd

      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy
          wranglerVersion: "4"
          workingDirectory: web