name: Release

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true

permissions:
  contents: write

jobs:
  create-release:
    uses: ./.github/workflows/create-release.yml

  build-windows:
    needs: create-release
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  build-linux:
    needs: create-release
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  publish:
    needs:
      - create-release
      - build-windows
      - build-linux

    runs-on: ubuntu-latest

    steps:
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.create-release.outputs.tag }}
          draft: false
