# Generated by Django 6.0 on 2026-02-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="notifications_frames/"
            ),
        ),
    ]
