# Generated by Django 6.0 on 2026-03-26 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cameras", "0006_alter_camera_options_alter_localcamera_options_and_more"),
        ("notifications", "0004_alter_notification_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="description",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="level",
            field=models.CharField(
                choices=[
                    ("I", "Informação"),
                    ("E", "Erro"),
                    ("S", "Suspeito"),
                    ("P", "Perigo"),
                ],
                max_length=1,
                verbose_name="Nível",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="readed",
            field=models.BooleanField(default=False, verbose_name="Lida"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=50, verbose_name="Título"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilizador",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "readed", "deleted"],
                name="notificatio_user_id_248330_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_46ad24_idx"
            ),
        ),
    ]
